### ISSUE TITLE
Implement AI players

### ISSUE THREAD

**Issue by notexactlyawe** [notexactlyawe/negativei2-server#44]
One extension for the server is to enable AI players. There are a number of questions to answer when implementing this.
 - What level should the AIs be at?
 - Should the level be configurable?
 - How can we do this and still deploy on Heroku? Python-chess [allows communication with engines](https://python-chess.readthedocs.io/en/latest/engine.html) like Stockfish, but presumably we have to have it running on the machine.
 - Will the server structure need to change? Or will this just affect `/makemove`.
 - If the AI can play first, how do we initiate their move?
 - How does the AI run down a clock? Do they have a clock?

For this to be properly effective we also need to implement waiting for the controller to finish its job. Up until now we've relied on the player taking time to allow the controller to make moves in time, but what about an AI that makes moves in ~100ms?

**Comment by eonu** [comment]
Implemented by #53.
